USE [master]
GO

/****** Object:  Database [CMMonitor]    Script Date: 6/14/2015 2:18:30 PM ******/
CREATE DATABASE [CMMonitor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CMMonitor', FILENAME = N'H:\SQLDB\CMMonitor.mdf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB )
 LOG ON 
( NAME = N'CMMonitor_log', FILENAME = N'I:\SQLLog\CMMonitor.ldf' , SIZE = 524288KB , MAXSIZE = 2097152KB , FILEGROWTH = 262144KB )
GO

ALTER DATABASE [CMMonitor] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC [CMMonitor].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [CMMonitor] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CMMonitor] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CMMonitor] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CMMonitor] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CMMonitor] SET ARITHABORT OFF 
GO

ALTER DATABASE [CMMonitor] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CMMonitor] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CMMonitor] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CMMonitor] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CMMonitor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CMMonitor] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CMMonitor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CMMonitor] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CMMonitor] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CMMonitor] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CMMonitor] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CMMonitor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CMMonitor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CMMonitor] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CMMonitor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CMMonitor] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CMMonitor] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CMMonitor] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CMMonitor] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CMMonitor] SET  MULTI_USER 
GO

ALTER DATABASE [CMMonitor] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CMMonitor] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CMMonitor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CMMonitor] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CMMonitor] SET  READ_WRITE 
GO


